### ISSUE TITLE
bug: Notification not working

### ISSUE THREAD

**Issue by vasav-prashar** [MS07062000/To_Do_List_App#5]
not getting the notifications

**Comment by muraliSingh7** [comment]
1. Ensure that location permission is set to allow at all times.
2. Ensure that both your Wi-Fi or internet services and location services are enabled. This will trigger a foreground service that will continue to run until the app is closed.
3. Check if notification permission is enabled or not. If not then enable it.
4. If any of the above points are not configured properly, the notification might not be triggered.
5. The app has been tested on Android 13 and is successfully throwing notifications.
6. I have set the radius to 10 meters. Whenever a person enters a radius of 10 meters from their desired location, and if the foreground services are running, then it will definitely trigger a notification.

**Comment by vasav-prashar** [comment]
I was trying the code which is present in repository...not working for me and also not giving the location list I also watched the video there is option of default location and in github app it shows my location can you please check on your side

**Comment by muraliSingh7** [comment]
I have updated few names after making video and it is working properly in my device which is on android 13. In home is it showing the list or note you made? If yes then location list might not show note or list because it is not for that current location. The radius is 10m that's why it might miss out by little margin.

**Comment by vasav-prashar** [comment]
thankyou Now working for me..
